#!/bin/sh
cd /root/authd
./authd &
sleep 1
cd /root/gacd
./gacd gamesys.conf &
sleep 2
cd /root/gdeliveryd
./gdeliveryd gamesys.conf &
sleep 3
cd /root/glinkd
./glinkd gamesys.conf 1 &
sleep 4
cd /root/gamedbd
./gamedbd gamesys.conf &
sleep 5
cd /root/uniquenamed
./uniquenamed gamesys.conf  &
sleep 6
cd /root/gamed
./gs gs.conf gmserver.conf gsalias.conf  &
sleep 7
