#!/bin/sh
cd /root/gdeliveryd
./gdeliveryd igamesys.conf &
sleep 2
cd /root/glinkd
./glinkd igamesys.conf 1 &
sleep 3
cd /root/gamedbd
./gamedbd igamesys.conf &
sleep 5
cd /root/gamed
./gs igs.conf igmserver.conf igsalias.conf  &
sleep 6
#cd /root/gamed
#./gs igs.conf igmserver.conf gsalias32.conf  &
#sleep 7